export enum ActionTypes {
  TOGGLE_ASIDE = 'TOGGLE_ASIDE',
  SET_AUTH_TRUE = 'SET_AUTH_TRUE',
  SET_AUTH_FALSE = 'SET_AUTH_FALSE',

  FETCH_CURRENCY_START = 'FETCH_CURRENCY_START',
  FETCH_CURRENCY_SUCCESS = 'FETCH_CURRENCY_SUCCESS',
  FETCH_CURRENCY_ERROR = 'FETCH_CURRENCY_ERROR',

  REGISTER_START = 'REGISTER_START',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_ERROR = 'REGISTER_ERROR',

  LOGIN_START = 'LOGIN_START',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_ERROR = 'LOGIN_ERROR',

  SET_USER = 'SET_USER',

  POST_USER_START = 'POST_USER_START',
  POST_USER_SUCCESS = 'POST_USER_SUCCESS',
  POST_USER_ERROR = 'POST_USER_ERROR',

  FETCH_USER_START = 'FETCH_USER_START',
  FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
  FETCH_USER_ERROR = 'FETCH_USER_ERROR',

  UPDATE_USER_START = 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
  UPDATE_USER_ERROR = 'UPDATE_USER_ERROR',

  CREATE_CATEGORY_START = 'CREATE_CATEGORY_START',
  CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR',

  FETCH_CATEGORY_START = 'FETCH_CATEGORY_START',
  FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR',

  UPDATE_CATEGORY_START = 'UPDATE_CATEGORY_START',
  UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS',
  UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR',

  CREATE_RECORD_START = 'CREATE_RECORD_START',
  CREATE_RECORD_SUCCESS = 'CREATE_RECORD_SUCCESS',
  CREATE_RECORD_ERROR = 'CREATE_RECORD_ERROR',

  FETCH_RECORD_START = 'FETCH_RECORD_START',
  FETCH_RECORD_SUCCESS = 'FETCH_RECORD_SUCCESS',
  FETCH_RECORD_ERROR = 'FETCH_RECORD_ERROR',
}
